name: Upload Static Site to GCS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Static Site to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: ./roomatch/html
          destination: roomatch-prod-static-site
          parent: false
          gzip: true
          resumable: true
          concurrency: 100
          process_gcloudignore: true
        env:
          CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ secrets.GCP_CREDENTIALS_PATH }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_PATH }}
          GOOGLE_GHA_CREDS_PATH: ${{ secrets.GCP_CREDENTIALS_PATH }}
          CLOUDSDK_CORE_PROJECT: roomatch-prod
          CLOUDSDK_PROJECT: roomatch-prod
          GCLOUD_PROJECT: roomatch-prod
          GCP_PROJECT: roomatch-prod
          GOOGLE_CLOUD_PROJECT: roomatch-prod 